# Generated by Django 3.2.7 on 2022-04-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='adress',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='adress_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='link_text',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
