# Generated by Django 3.2.7 on 2022-04-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
