# Generated by Django 3.2.7 on 2022-04-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_event_is_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='event',
            name='link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='link_text',
        ),
    ]
