# Generated by Django 3.2.7 on 2022-04-27 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0010_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtemplate',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants_template_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
