# Generated by Django 3.2.7 on 2022-04-28 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0011_eventtemplate_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtemplate',
            name='participants',
        ),
        migrations.AddField(
            model_name='event',
            name='invites',
            field=models.ManyToManyField(blank=True, related_name='invites_event_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='invites',
            field=models.ManyToManyField(blank=True, related_name='invites_template_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
